AgainIoT/Open-Set-Go_client

src/components/common/Stepper.js, src/layout/Header.js, src/layout/Layout.js, src/routes/router.js, src/styles/color.js
Implementation of stepper and common frame
#1 
UI
- [ x ] New feature (changes which adds functionality)
=> Feature/1 #1

.gitmessage.txt
=> Fix : typo error on .gitmessage.txt fixed #9

package.json, src/pages/Login.js, src/pages/MainPage.js, src/routes/router.js, yarn.lock
- GitHub Login feature added
- .env added
- GitHub Login API linked with Open-Set-Go_server
#14
=> Feat : GitHub Login feature added #14

.eslintrc.yml, package.json, src/components/common/Autocomplete.js, src/components/common/InputComponent.js, src/components/common/SearchAuto.js, src/components/common/SelectChip.js, src/components/common/ShowSelect.js, src/components/common/modal/BaseModal.js, src/components/common/modal/gitignoreModal.js, src/components/common/step1/gitignoreContainer.js, src/data/CreateRepoData.js, src/index.js, src/pages/CreateRepoPage.js, src/recoil/openModal.js, src/recoil/repoData.js, src/routes/router.js, src/styles/color.js, src/styles/globalStyle.js
- Implementation of components for Create repo step page UI
- Implementation of components & feature related to gitignore
#10 
=> Feature/10 #10

README.md
=> Docs : README.md added #22

src/pages/ContributingTemplatePage.js, src/pages/PRTemplatePage.js, src/pages/ReadmeTemplatePage.js
=> Design : Remove Modal Button and Save Button #59

package.json, yarn.lock
- https://github.com/AgainIoT/Open-Set-Go_client/security/dependabot/3
resolved postcss version to ^8.4.31
=> Fix : vulnerability alert resolved  #77

package.json, src/components/main/Welcome.js, src/index.js, src/layout/Header.js, src/pages/Login.js, src/pages/MainPage.js, src/recoil/authorize.js, yarn.lock
It's written well in the issue #78 
=> cookie handling

package.json
add react script `yarn start:win` & `yarn start:linux`
#85
=> Add : add react script 'yarn start:win' & 'yarn start:linux' #85

CONTRIBUTING.md, README.md, src/components/main/Footer.js, src/layout/Header.js
Hot-Fix for applying changed domain of open-set-go.io
#88
=> Fix : blog -> docs, docs domain changed #88

public/index.html
Logo.svg changed to logo.svg(typo error)
Co-authored-by : bent_shrimp <bent_shrimp@kookmin.ac.kr>
=> Fix : Logo.svg changed to logo.svg(typo error)

public/index.html
=> Unexpected bugs fixed

src/layout/Header.js, src/pages/MainPage.js
Reverts AgainIoT/Open-Set-Go_client#94
=> Revert "Unexpected bugs fixed"

src/layout/Header.js, src/pages/MainPage.js
=> Fix : manage login state only in Header #83

public/index.html
=> profile image rendering problem fix

src/components/common/Slide.js, src/components/common/SlideContent.js, src/components/common/template/GenerateList.js
In the Open-Set-Go_server, a security vulnerability has been found in the license portion. The part could be modified in https://github.com/AgainIoT/Open-Set-Go_server/issues/104, which changed the license's Data Format. In line with this, we want to apply it to the Client.
Open-Set-Go_server에서는 License 부분에서 보안 취약점이 발견된 바가 있다. 해당 부분을 https://github.com/AgainIoT/Open-Set-Go_server/issues/104 에서 수정할 수 있었는데, 이에 따라서 License의 Data Format이 변경되었다. 이에 맞추어 Client에서도 적용시키고자 한다.
#116
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
=> Fix : License problems resolved at #116

src/components/common/template/TemplateList.js
ListItem on TemplateList.js looks too ugly, so I fixed it. Tell me how you think of it.
#114 
=> Improve list item layout #114

src/components/common/template/GenerateList.js, src/components/common/template/TemplateList.js, src/data/ListItem.js, src/data/ListItemData.js
Template data from the server was reassigned by disassembling and assembling. Just like the code below.
```node.js
function refine(data) {
const ret = [];
data.map((value) => {
const tmp = {
_id: value._id,
index: value.index,
title: value.type,
subtitle: null,
repoUrl: null,
content: value.content,
};
ret.push(tmp);
});
return ret.sort((a, b) => a.index - b.index);
}
```
But now it looks much more clean
```node.js
function refine(data) {
const dataList = data.map((value) => {
const id = value._id;
const index = value.index;
const title = value.type;
const content = value.content;
new DraggableListItemData(id, title, index, content);
});
return dataList.sort((a, b) => a.index - b.index);
}
```
#118 
_Put an `x` in the …
=> react against server change & manage ListItem data with class

src/components/common/MarkdownPreview.js, src/components/common/SelectAuto.js, src/components/common/Slide.js, src/components/common/modal/TemplateModal.js, src/components/step1/GitignoreContainer.js, src/components/step1/RequiredFieldContainer.js, src/components/step1/SelectContainer.js, src/layout/Layout.js, src/pages/ContributingTemplatePage.js, src/pages/CreateRepoPage.js, src/pages/PRTemplatePage.js, src/pages/ReadmeTemplatePage.js
How do you think it is? Let's fix it together.
#120 
=> Fix everything looks wrong on step pages

src/components/common/SlideContent.js
you press select button, it turns into cancel button.
Only one or less button can be selected
#124 
=> Deselect on license page

src/components/common/modal/BaseDialog.js, src/components/common/modal/BaseModal.js, src/components/common/modal/GitignoreModal.js, src/components/common/modal/TemplateModal.js, src/components/common/template/LIstUtils.js, src/components/common/template/StyledTemplate.js, src/components/common/template/TemplateBody.js, src/components/common/template/TemplateTitle.js
- markdown preview size and position problem fixed
- you can close the modal by pressing 'use template' or 'exit' button
- removed Search for demonstration
=> Fix : TemplateModal layout & removed Search for demonstration

src/components/common/modal/ReviewDialog.js, src/pages/ReviewIssueTemplatePage.js, src/routes/router.js
=> Create a IssuePage that occurs when you add new features in a review

src/components/step1/RequiredFieldContainer.js
Add 'dataState' to fix error about missing prop 'dataState'
#161
=> Fix error about missing 'dataState' prop

src/components/common/IssueChip.js, src/components/common/SelectType.js, src/components/common/modal/CancelDialog.js, src/components/common/modal/ReviewDialog.js, src/components/review/FirstContents.js, src/components/review/SecondContents.js, src/components/step1/RequiredFieldContainer.js, src/data/ReviewItemData.js, src/layout/Header.js, src/layout/Layout.js, src/pages/ReviewContributingTemplatePage.js, src/pages/ReviewIssueTemplatePage.js, src/pages/ReviewPRTemplatePage.js, src/pages/ReviewReadmeTemplatePage.js, src/recoil/reviewState.js, src/routes/router.js
Navigate the review page to a new page that occurs when you add new features in a review.
The files that can be added through the new function are as follows.
#157
=> Navigate the review page to a new page that occurs when you add new features in a review

src/components/common/SlideContent.js
Apply the select color appropriately and apply the border according to when selected and when not.
#159
=> Modify the color of the select button

src/layout/Header.js, src/pages/Login.js, src/recoil/authorize.js
Once user finish creating repository, not only the repository data but also the user data was being missing.
Now it has been fixed.
#139 
=> Fix : User login data persist problem

src/components/common/modal/FinishDialog.js
=> Fix : complete button is activated only for the first click

src/components/common/MarkdownPreview.js
little change. so just compare this with now and tell me which is better.
작은 변경 사항이에요. 그러니 그냥 지금이랑 비교해서 뭐가 더 좋은지 알려주세요.
#164 
=> Update : put the markdown preview in the middle #164

src/components/main/Welcome.js, src/layout/Header.js
press the learn more button and check out if the header doesn't hide the content.
learn more 버튼 눌러서 헤더가 내용을 가리는지 확인해보세요.
=> Fix : added offset to the scroll destination

src/components/common/modal/FinishDialog.js, src/components/common/template/TemplateList.js
- only first one click is available
- navigate to step1 if the repo already exists
See what happens at these cases.
=> Fix : handle exception during create repository

src/components/common/IssueChip.js, src/components/common/IssueList.js, src/components/common/modal/IssueModal.js
Fixed an issue that is deleted only on the UI when deleting an issue template.
-> Modified code to be deleted from objects sent to server.
Supplement by handing over the title to the server as a type instead of the title.
#198 
=> Fix : fix some bug in issue step

src/components/common/SelectType.js, src/pages/SelectTypePage.js
change p tag to typography
#196
=> Chore : change p tag to typography #196

.github/ISSUE_TEMPLATE/BugReport.yml, .github/ISSUE_TEMPLATE/Documentation.yml, .github/ISSUE_TEMPLATE/FeatureRequest.yml, .github/ISSUE_TEMPLATE/Refactor.yml, .github/ISSUE_TEMPLATE/config.yml, README.md
=> Docs : issue templates renewal #68

.github/ISSUE_TEMPLATE/BugReport.yml, .github/ISSUE_TEMPLATE/Documentation.yml, .github/ISSUE_TEMPLATE/FeatureRequest.yml, .github/ISSUE_TEMPLATE/Refactor.yml, .github/ISSUE_TEMPLATE/config.yml, README.md, public/robots.txt, src/components/common/modal/ReviewDialog.js
- Review Feature's Making Issue Template bug resolved at #207 & AgainIoT/Open-Set-Go#68
=> Open-Set-Go v2.0.1 HOTFIX released 

public/index.html
open graph meta tags for twitter added
#211 
=> Fix : add open graph meta tags
